apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: systemzero
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: systemzero.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: systemzero
                port:
                  number: 80
